package com.sergioricart.notification_service.notification.infrastructure.event.consumer.user.specific;

import com.sergioricart.commons.application.Mediator;
import com.sergioricart.commons.infrastructure.event.consumer.EventSpecificConsumer;
import com.sergioricart.notification_service.notification.aplication.kafka.user.deleted.UserDeletedCommand;
import com.sergioricart.notification_service.notification.infrastructure.event.mapper.user.UserEventMapper;
import com.sergioricart.user_service.autogenerated.events.user.UserDeletedEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserDeletedConsumer implements EventSpecificConsumer<UserDeletedEvent> {

    private final Mediator mediator;

    private final UserEventMapper userEventMapper;

    @Override
    public String getSchema() {
        return UserDeletedEvent.class.getTypeName();
    }

    @Override
    public void accept(Message<UserDeletedEvent> message) {

        UserDeletedEvent event = message.getPayload();

        log.info("Usuario eliminado: {}", event.getId());

        UserDeletedCommand command = userEventMapper.mapToUserDeletedCommand(event);

        mediator.dispatch(command);

    }
}
