package com.sergioricart.notification_service.notification.infrastructure.event.consumer.user.specific;

import com.sergioricart.commons.application.Mediator;
import com.sergioricart.commons.infrastructure.event.consumer.EventSpecificConsumer;
import com.sergioricart.notification_service.notification.aplication.kafka.user.created.UserCreatedCommand;
import com.sergioricart.notification_service.notification.aplication.kafka.user.updated.UserUpdatedCommand;
import com.sergioricart.notification_service.notification.infrastructure.event.mapper.user.UserEventMapper;
import com.sergioricart.user_service.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.user_service.autogenerated.events.user.UserUpdatedEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserUpdatedConsumer implements EventSpecificConsumer<UserUpdatedEvent> {

    private final Mediator mediator;

    private final UserEventMapper userEventMapper;

    @Override
    public String getSchema() {
        return UserUpdatedEvent.class.getTypeName();
    }

    @Override
    public void accept(Message<UserUpdatedEvent> message) {

        UserUpdatedEvent event = message.getPayload();

        log.info("Usuario creado: {} {}, email: {}", event.getFirstName(), event.getLastName(), event.getEmail());

        UserUpdatedCommand command = userEventMapper.mapToUserUpdatedCommand(event);

        mediator.dispatch(command);

    }
}
