package com.sergioricart.notification_service.notification.infrastructure.event.mapper.user;

import com.sergioricart.notification_service.notification.aplication.kafka.user.created.UserCreatedCommand;
import com.sergioricart.notification_service.notification.aplication.kafka.user.deleted.UserDeletedCommand;
import com.sergioricart.notification_service.notification.aplication.kafka.user.updated.UserUpdatedCommand;
import com.sergioricart.user_service.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.user_service.autogenerated.events.user.UserDeletedEvent;
import com.sergioricart.user_service.autogenerated.events.user.UserUpdatedEvent;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper {

    UserCreatedCommand mapToUserCreatedCommand(UserCreatedEvent event);

    UserUpdatedCommand mapToUserUpdatedCommand(UserUpdatedEvent event);

    UserDeletedCommand mapToUserDeletedCommand(UserDeletedEvent event);

    default String map(CharSequence value) {
        return value != null ? value.toString() : null;
    }

}
